name: Push/pull tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        script:
        - push-docker-pull-docker.sh
        - push-docker-pull-containerd.sh
        - push-containerd-pull-docker.sh
        - push-containerd-pull-containerd.sh

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: "Use Node.js 15"
      with:
        node-version: "15"
    - uses: crazy-max/ghaction-setup-containerd@v1
      name: Set up containerd
    - run: sudo apt update && sudo apt install libsodium23 libsodium-dev
      name: Install libsodium
    - run: npm ci
      name: Installing whalesong
    - run: WHALESONG_DEBUG_ROUTES=1 DEBUG="*,-koa-router,-hypercore" node index.js &
      name: Launching an instance of whalesong in the background
    - run: sudo bash ${{ matrix.script }}
      working-directory: tests
      name: Run push/pull test ${{ matrix.script }}
