name: Node.js tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      name: "Use Node.js 15"
      with:
        node-version: "15"
    - run: npm i
      name: Installing whalesong
    - run: npm test
      name: Run lint and test
